zh:
  - "zh-CN-XiaochenNeural"
  - "zh-CN-XiaohanNeural"
  - "zh-CN-XiaomengNeural"
  - "zh-CN-XiaomoNeural"
  - "zh-CN-XiaoqiuNeural"
  - "zh-CN-XiaoruiNeural"
  - "zh-CN-XiaoshuangNeural"
  - "zh-CN-XiaoxiaoNeural"
  - "zh-CN-XiaoxuanNeural"
  - "zh-CN-XiaoyanNeural"
  - "zh-CN-XiaoyiNeural"
  - "zh-CN-XiaoyouNeural"
  - "zh-CN-XiaozhenNeural"
  - "zh-CN-YunfengNeural"
  - "zh-CN-YunhaoNeural"
  - "zh-CN-YunjianNeural"
  - "zh-CN-YunxiaNeural"
  - "zh-CN-YunxiNeural"
  - "zh-CN-YunyangNeural"
  - "zh-CN-YunyeNeural"
  - "zh-CN-YunzeNeural"
en:
  - "en-US-AIGenerate1Neural1"
  - "en-US-AIGenerate2Neural1"
  - "en-US-AmberNeural"
  - "en-US-AnaNeural"
  - "en-US-AriaNeural"
  - "en-US-AshleyNeural"
  - "en-US-BrandonNeural"
  - "en-US-ChristopherNeural"
  - "en-US-CoraNeural"
  - "en-US-DavisNeural"
  - "en-US-ElizabethNeural"
  - "en-US-EricNeural"
  - "en-US-GuyNeural"
  - "en-US-JacobNeural"
  - "en-US-JaneNeural"
  - "en-US-JasonNeural"
  - "en-US-JennyMultilingualNeural3"
  - "en-US-JennyNeural"
  - "en-US-MichelleNeural"
  - "en-US-MonicaNeural"
  - "en-US-NancyNeural"
  - "en-US-RogerNeural1"
  - "en-US-SaraNeural"
  - "en-US-SteffanNeural"
  - "en-US-TonyNeural"
